# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('suscriber_number', models.TextField()),
                ('access_token', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('role', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
