# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_suscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriber',
            name='access_token',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='suscriber',
            name='address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='suscriber',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='suscriber',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='suscriber',
            name='suscriber_number',
            field=models.CharField(max_length=10),
        ),
    ]
