# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20170724_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriber',
            old_name='suscriber_number',
            new_name='subscriber_number',
        ),
    ]
