# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_auto_20170725_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriber',
            new_name='Subscriber',
        ),
    ]
