# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20170725_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='oxygen_level',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='pH_level',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='temperature_level',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
