# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20170727_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
