# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20170727_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='access_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_number',
            field=models.CharField(max_length=11),
        ),
    ]
