# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_auto_20170824_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
