# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_auto_20170830_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feeder_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
