# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_report_feeder_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='feeder_grams',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
