# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_auto_20170830_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='feed_number',
        ),
        migrations.AddField(
            model_name='report',
            name='fish_feed_grams',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
