# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_auto_20170911_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feed_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
