# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_report_feed_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='v1.Subscriber')),
                ('command', models.TextField(max_length='10')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
