# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0024_commandlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlog',
            name='command',
            field=models.CharField(max_length=10),
        ),
    ]
