# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0026_manualcommandlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcommandlog',
            name='web',
            field=models.BooleanField(default=False),
        ),
    ]
