# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_manualcommandlog_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=40)),
                ('amount', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
