# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
