# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0029_auto_20180726_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='contract_address',
            field=models.CharField(default='BTC', max_length=100),
            preserve_default=False,
        ),
    ]
