# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0032_testing_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
