# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0035_testing_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='script_hash',
            field=models.CharField(default='haha', max_length=100),
            preserve_default=False,
        ),
    ]
